# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
send_funds_to: shaynemichaelbacik@outlook.com,or_"shaynebacik163@gmail.com,or_account#"830513177378","transit#"50138"_",route#"889".I_need_financial_aid_i_cant_,figure_out_,how_to,_withdrawl_any_amount_and_im_dealing,_,with_,identity_fraud_as_well_as_theft_,in_the_highest_degree_pleasehelp.
operation_save_Shayne_Michael_Bacik.also,Ihave the withdrawal credentials for every token,crytpo and currencys_that_are_all_registered_,in_my_name_on_the_blockchains_so_its_very_simple_i_just_need_a_partner_or_a_coomunity_based_freindship.My goal is to have the first crypto,token,currency and alot more _ABank_called,GlobalWealthBank_OwnerS??????"to;be developed.
